auto: true
server: true
permalink: none
baseurl: "/damani"
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    _posts/pages: |
      published: false
      layout: page
      title: Your Post Title
      abstract: Short summary of your page.
      author: Damani Parin
      caption: A quote or caption.
      caption-attribute: Quote attribution
      image:
      permalink: title.html
      tags:
      - test
    _posts/blocks: |
      published: false
      layout: block
      title: Your Block Title
      permalink: blocks/title.html
      tags:
      - block